//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpCtrlClientManager.ImpService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImpService.IImpStatusService", CallbackContract=typeof(ImpCtrlClientManager.ImpService.IImpStatusServiceCallback))]
    public interface IImpStatusService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/RegistrCallbackClientFunc", ReplyAction="http://tempuri.org/IImpStatusService/RegistrCallbackClientFuncResponse")]
        void RegistrCallbackClientFunc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/RegistrCallbackClientFunc", ReplyAction="http://tempuri.org/IImpStatusService/RegistrCallbackClientFuncResponse")]
        System.Threading.Tasks.Task RegistrCallbackClientFuncAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetLastSatus", ReplyAction="http://tempuri.org/IImpStatusService/GetLastSatusResponse")]
        string GetLastSatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetLastSatus", ReplyAction="http://tempuri.org/IImpStatusService/GetLastSatusResponse")]
        System.Threading.Tasks.Task<string> GetLastSatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetImageStatus", ReplyAction="http://tempuri.org/IImpStatusService/GetImageStatusResponse")]
        System.Drawing.Image GetImageStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetImageStatus", ReplyAction="http://tempuri.org/IImpStatusService/GetImageStatusResponse")]
        System.Threading.Tasks.Task<System.Drawing.Image> GetImageStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetScreenshot", ReplyAction="http://tempuri.org/IImpStatusService/GetScreenshotResponse")]
        byte[] GetScreenshot();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetScreenshot", ReplyAction="http://tempuri.org/IImpStatusService/GetScreenshotResponse")]
        System.Threading.Tasks.Task<byte[]> GetScreenshotAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetFullLog", ReplyAction="http://tempuri.org/IImpStatusService/GetFullLogResponse")]
        string[] GetFullLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetFullLog", ReplyAction="http://tempuri.org/IImpStatusService/GetFullLogResponse")]
        System.Threading.Tasks.Task<string[]> GetFullLogAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetImportProtocol", ReplyAction="http://tempuri.org/IImpStatusService/GetImportProtocolResponse")]
        string GetImportProtocol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IImpStatusService/GetImportProtocol", ReplyAction="http://tempuri.org/IImpStatusService/GetImportProtocolResponse")]
        System.Threading.Tasks.Task<string> GetImportProtocolAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImpStatusServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IImpStatusService/OnStatusComplete")]
        void OnStatusComplete(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IImpStatusServiceChannel : ImpCtrlClientManager.ImpService.IImpStatusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImpStatusServiceClient : System.ServiceModel.DuplexClientBase<ImpCtrlClientManager.ImpService.IImpStatusService>, ImpCtrlClientManager.ImpService.IImpStatusService {
        
        public ImpStatusServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ImpStatusServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ImpStatusServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ImpStatusServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ImpStatusServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void RegistrCallbackClientFunc() {
            base.Channel.RegistrCallbackClientFunc();
        }
        
        public System.Threading.Tasks.Task RegistrCallbackClientFuncAsync() {
            return base.Channel.RegistrCallbackClientFuncAsync();
        }
        
        public string GetLastSatus() {
            return base.Channel.GetLastSatus();
        }
        
        public System.Threading.Tasks.Task<string> GetLastSatusAsync() {
            return base.Channel.GetLastSatusAsync();
        }
        
        public System.Drawing.Image GetImageStatus() {
            return base.Channel.GetImageStatus();
        }
        
        public System.Threading.Tasks.Task<System.Drawing.Image> GetImageStatusAsync() {
            return base.Channel.GetImageStatusAsync();
        }
        
        public byte[] GetScreenshot() {
            return base.Channel.GetScreenshot();
        }
        
        public System.Threading.Tasks.Task<byte[]> GetScreenshotAsync() {
            return base.Channel.GetScreenshotAsync();
        }
        
        public string[] GetFullLog() {
            return base.Channel.GetFullLog();
        }
        
        public System.Threading.Tasks.Task<string[]> GetFullLogAsync() {
            return base.Channel.GetFullLogAsync();
        }
        
        public string GetImportProtocol() {
            return base.Channel.GetImportProtocol();
        }
        
        public System.Threading.Tasks.Task<string> GetImportProtocolAsync() {
            return base.Channel.GetImportProtocolAsync();
        }
    }
}
